### ISSUE TITLE
Uncaught Error: Class 'Scheduler\Job\CronRule' not found

### ISSUE THREAD

**Issue by ankurpramanik** [hutnikau/job-scheduler#23]
@hutnikau    I followed step by step configuration and write code but below mentioned exception is coming:

PHP Fatal error:  Uncaught Error: Class 'Scheduler\Job\CronRule' not found in D:\Project\PHP\scheduler1\src\run.php:3
Stack trace:
#0 {main}
  thrown in D:\Project\PHP\scheduler1\src\run.php on line 3

![1](https://user-images.githubusercontent.com/40001115/69526413-22191d80-0f90-11ea-8254-69f90545e6dd.JPG)
![2](https://user-images.githubusercontent.com/40001115/69526416-23e2e100-0f90-11ea-8bd5-1a7d91983da6.JPG)
![3](https://user-images.githubusercontent.com/40001115/69526418-25aca480-0f90-11ea-9ad9-2232445746f8.JPG)

**Comment by hutnikau** [comment]
Hello @ankurpramanik ,
Thanks for reporting the issue.

Looks like you did not include `autoload.php` file.
Try to add this line at the very beginning of your `run.php` file:

```php
require __DIR__ . '/../vendor/autoload.php';
```

**Comment by ankurpramanik** [comment]
Thank You. @hutnikau
