### ISSUE TITLE
Task is not running

### ISSUE THREAD

**Issue by ankurpramanik** [hutnikau/job-scheduler#24]
@hutnikau 
I have created a scheduler using this library but not running when run as php CLI.

```<?php
use Scheduler\Job\CronRule;
use Scheduler\Job\Job;
use Scheduler\JobRunner\JobRunner;
use Scheduler\Scheduler;

require __DIR__ . '/../vendor/autoload.php';

$executionTime = new DateTime('2019-11-26'); //I need to get current system time automatically
echo (string) $executionTime->format('d/M/Y h:m:s');

$rule = new CronRule('*/1 * * * *', $executionTime); // This will execute at every min
$job = new Job($rule, function () {
    echo "Hello";
});

$scheduler = new Scheduler();
$scheduler->addJob($job);

$jobRunner = new JobRunner();
$reports = $jobRunner->run($scheduler, $executionTime, null, true); 
// I dont want to stop the work and I don't want to give a specific time to start. It will start immidiately
```

![2](https://user-images.githubusercontent.com/40001115/69607703-d166fa80-104b-11ea-9c7b-96297305d7d8.png)

![1](https://user-images.githubusercontent.com/40001115/69609760-4b00e780-1050-11ea-84e7-cbe667bf87fa.JPG)

It is printing all the hello at a time not cron string wise

Please answer this question

**Comment by hutnikau** [comment]
I think you need to use Worker
Please read the documentation and do not create issues when you need consultation or assistance.

Issues supposed only to report a bug.
